### ISSUE TITLE
"Cache enabled" toggle not found in the UI

### ISSUE THREAD

**Issue by tylere** [fusedio/fused-docs#191]
https://docs.fused.io/workbench/udf-builder/code-editor/#cache
shows a screenshot with a "cache enabled" toggle:
![image](https://github.com/user-attachments/assets/55d796b0-9aaf-4520-9ebe-172ca645aab3)
but the current workbench UI does not show that toggle:
![Screenshot 2024-09-27 at 3 43 01 PM](https://github.com/user-attachments/assets/934abb77-c3df-4adf-a052-c5288800f51d)

Did the "cache enabled" toggle move elsewhere?

**Comment by pgzmnk** [comment]
The UDF must first be saved for this to show up.

**Comment by tylere** [comment]
Makes sense. Given that, I would suggest:
- starting the [Cache](https://docs.fused.io/workbench/udf-builder/code-editor/#cache) section by explaining how to enable caching of a UDF

**Comment by pgzmnk** [comment]
Thank you for the feedback. 

https://github.com/fusedio/fused-docs/pull/194
